# -*- coding: utf-8 -*-
"""Coffee.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QxR0t5d0U76xBgTTcj83ie9oieb5jsHl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import OrdinalEncoder
import pickle

def cups_clean(x):
  print("DEBUG: Running cups_clean")
    # 1. Input Fix: Handle the DataFrame from the Pipeline
  if isinstance(x, pd.DataFrame):
    x = x.iloc[:, 0]

  cups_map = {
        'less than 1': 0.5,
        '1': 1.0,
        '2': 2.0,
        '3': 3.0,
        '4': 4.0,
        'more than 4': 5.0
  }

  y = x.map(cups_map).fillna(2.0)

  #Return as a 2D array for the next step
  return y.values.reshape(-1, 1)

cups_transform = FunctionTransformer(cups_clean)

def strength_clean(x):
  print("DEBUG: Running strength_clean")
  if isinstance(x, pd.DataFrame):
    x = x.iloc[:, 0]
  strength_map = {
      'Somewhat light' : 1,
      'Weak'           : 1,
      'Medium'         : 2,
      'Somewhat strong': 3,
      'Very strong'    : 3
  }
  y = x.map(strength_map).fillna(2)

  # 3. Return as a 2D array (required by Scikit-Learn)
  return y.values.reshape(-1, 1)

strength_transform = FunctionTransformer(strength_clean)

def caffeine_clean(x):
  print("DEBUG: Running caffeine_clean")

  # 1. Input Fix: Ensure we have a 2D format for the encoder
  if isinstance(x, pd.Series):
    x = x.to_frame()
  elif not isinstance(x, pd.DataFrame):
     # If it's a numpy array, make it 2D
    x = x.reshape(-1, 1)
  #Decaf : 1, Half caff : 2 , Full caffeine : 3
  caffeine_order= ['Decaf','Half caff','Full caffeine']
  enc = OrdinalEncoder(categories=[caffeine_order],
                         handle_unknown='use_encoded_value',
                         unknown_value=-1)
  y = enc.fit_transform(pd.DataFrame(x).fillna('Full caffeine'))
  return y

caffeine_transform = FunctionTransformer(caffeine_clean)

def expertise_clean(x):
  print("DEBUG: Running expertise_clean")
  if isinstance(x, pd.DataFrame):
    x = x.iloc[:, 0]
  # 'coerce' turns text like "Other" into NaN (empty values)
  y = pd.to_numeric(x, errors= 'coerce').fillna(5)
  return y.values.reshape(-1, 1)

expertise_transform = FunctionTransformer(expertise_clean)

def gender_clean(x):
  print("DEBUG: Running gender_clean")
  if isinstance(x, pd.DataFrame):
    x = x.iloc[:, 0]

  gender_map = {
    'Male': 0,
    'Female': 1,
    'Non-binary': 2,
    'Prefer not to say': 2,
    'Other': 2
  }
  y = x.map(gender_map).fillna(2)

  return y.values.reshape(-1, 1)

gender_transform = FunctionTransformer(gender_clean)

def map_willingness(value):

  value = str(value).lower()
  if '$0-$2' in value or '$2-$4' in value:
    return 1 # Budget/Traditional
  elif '$4-$6' in value or '$6-$8' in value:
    return 2 # Mid-range/Specialty
  else:
    return 3 # Premium/Experimental

def most_willing_clean(x):
  print("DEBUG: Running most_willing_clean")
  #FIX THE INPUT (from 2D table to 1D list)
  if isinstance(x, pd.DataFrame):
    x = x.iloc[:, 0]

  y = x.apply(map_willingness)
  return y.values.reshape(-1, 1)

willing_transform = FunctionTransformer(most_willing_clean)

def brew_clean(x):
  print("DEBUG: Running brew_clean")
    # Ensure input is a DataFrame
  temp_df = pd.DataFrame(x)
  col_name = temp_df.columns[0]

  methods = ['Pour over', 'Espresso', 'French press', 'Drip coffee',
               'AeroPress', 'Pod/capsule', 'Instant coffee']

  new_df = pd.DataFrame(index=temp_df.index) # Keep the index for alignment

  for method in methods:

    new_name = f"brew_{method.lower().replace(' ', '_')}"
    # Use .str.contains to find the method anywhere in the string
    new_df[new_name] = temp_df[col_name].str.contains(method, case=False, na=False).astype(int)

  return new_df # Returns a 2D DataFrame with 7 columns

brew_transform = FunctionTransformer(brew_clean)

def fav_clean(x):

  print("DEBUG: Running fav_clean")
  # 1. Input Fix: Handle the DataFrame from the Pipeline
  if isinstance(x, pd.DataFrame):
    x = x.iloc[:, 0]

  fav_map = {
        'Blended drink (e.g. Frappuccino)': 1,
        'Mocha': 1,
        'Latte': 1,
        'Cappuccino': 1,
        'Regular drip coffee': 2,
        'Iced coffee': 2,
        'Americano': 2,
        'Cold brew': 2,
        'Other': 2,
        'Espresso': 3,
        'Cortado': 3,
        'Pourover': 4
  }

  y = x.map(fav_map).fillna(2)

  #Return as a 2D array
  return y.values.reshape(-1, 1)

fav_transform = FunctionTransformer(fav_clean)

def add_clean(x):
  print("DEBUG: Running add_clean")
  #Ensure input is a DataFrame
  temp_df = pd.DataFrame(x)
  col_name = temp_df.columns[0]

  # List the core additions we want to track
  additions = ['Milk', 'Sugar', 'Syrup', 'Sweetener', 'Creamer']

  # 2. Match the index to keep data aligned
  new_df = pd.DataFrame(index=temp_df.index)

  for a in additions:
    new_col = f"adds_{a.lower()}"
    new_df[new_col] = temp_df[col_name].str.contains(a, case=False, na=False).astype(int)

  return new_df

add_transform = FunctionTransformer(add_clean)

import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin

class CoffeePostFeatures(BaseEstimator, TransformerMixin):

    def __init__(self, feature_names):
        self.feature_names = feature_names

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        df = pd.DataFrame(X, columns=self.feature_names)

        # 1. Coffee Maturity
        df['coffee_maturity'] = df['age'] * df['expertise']

        # 2. Expert Intensity
        df['expert_intensity'] = df['cups'] * df['expertise']

        # 3. Premium Index
        df['premium_index'] = df['most_willing'] * df['brew_espresso']

        # 4. Sweetened Behavior
        df['sweetened_behavior'] = (
            df['adds_sugar'] +
            df['adds_syrup'] +
            df['adds_milk']
        )

        return df.values

